### ISSUE TITLE
nginx not behaving as the official image

### ISSUE THREAD

**Issue by metakermit** [marinaio/library#1]
In the [official nginx image docs](https://hub.docker.com/_/nginx/) they mention that adding *index.html* to */usr/share/nginx/html* should result in the container serving that content. Instead, on the container built by marina I get:

```
Welcome to nginx on Debian!
If you see this page, the nginx web server …
```

The example repo I'm using is [this one](https://github.com/metakermit/hello-marina/blob/master/Dockerfile).

I guess the nginx config file should be changed to match the official one.

**Comment by DoubleMalt** [comment]
Fixed
